config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'trips#index'
  resources :trips, except: :show do
    resources :events, except: :index
  end
  resources :notes, except: [:index, :show]
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :trip
  validates :title, presence: true, length: { in: 5..255 }
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :users
  validates :note, presence: true, length: { in: 2..255 }
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :users
  has_many :events, dependent: :destroy
  validates :name, presence: true, length: { in: 2..255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trips, dependent: :destroy
  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_up_path_for(_resource)
    root_path
  end

  def after_sign_in_path_for(_resource)
    root_path
  end

  def set_layout
    @while_layout = true
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :set_layout

  def create
    @trip = current_user.trips.find(params[:trip_id])
    @event = @trip.events.build(event_params)
    if @event.save
      redirect_to trip_event_path(@trip, @event)
    else
      render 'new'
    end
  end

  def new
    @trip = current_user.trips.find(params[:trip_id])
    @event = @trip.events.build
  end

  def edit
    @trip = current_user.trips.find(params[:trip_id])
    @event = get_event(params[:id])
  end

  def show
    @event = get_event(params[:id])
  end

  def update
    @event = get_event(params[:id])
    if @event.update(event_params[:id])
      redirect_to trip_event_path(@trip, @event)
    else
      render 'edit'
    end
  end

  def destroy
    @event = get_event(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private

  def get_event(id)
    current_user.trips.find(params[:trip_id]).events.find(id)
  end

  def event_params
    params.require(:event).permit(:title, :date, :time, :duration, :place, :notes)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, :set_layout

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def new
    @note = current_user.notes.new
  end

  def edit
    @note = get_note(params[:id])
  end

  def update
    @note = get_note(params[:id])
    if @note.update(note_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @note = get_note(params[:id])
    @note.destroy
    redirect_to root_path
  end

  private

  def get_note(id)
    current_user.notes.find(id)
  end

  def note_params
    params.require(:note).permit(:note)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!, :set_layout

  def create
    @trip = current_user.trips.build(trip_params)
    if @trip.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @trips = current_user.trips.all
    @notes = current_user.notes.all
  end

  def new
    @trip = current_user.trips.build
  end

  def show
    @trip = get_trip(params[:id])
    @events = @trip.events
  end

  def edit
    @trip = get_trip(params[:id])
  end

  def update
    @trip = get_trip(params[:id])
    if @trip.update(trip_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @trip = get_trip(params[:id])
    @trip.destroy
    redirect_to root_path
  end

  private

  def get_trip(id)
    current_user.trips.find(id)
  end

  def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pin_notes_helper.rb
module PinNotesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/days/index.html.erb
<% content_for :title do %>
  <title> Home | Trip Planner</title>
<% end %>

<div class="container">
  <div class="row full collapse">
    <div class="col-xs-12 col-md-8">
      <div class="row collapse">
        <div class="col-xs-12">
          <div class="panel navbar-panel">
            <h1>Trip Planner</h1>
            <%= link_to new_trip_plan_path, class: 'button secondary' do %>
              <i class="fa fa-plus-circle"></i>
              New
            <% end %>
          </div>
        </div>
      </div>
      <div class="row collapse">
        <div class="col-xs-1">
          <p class="text-right">
            <%= link_to new_trip_plan_path, class: 'new-plan' do %>
              <i class="fa fa-plus-circle">
            <% end %>
          </div>
        <div class="col-xs-11">
          <% @days.each do |i| %>
            <div class="day">
              <div class="row">
                <div class="col-xs-12">
                  <%= link_to i.day, i, class: 'button round secondary' %>
                  <%= link_to 'Delete', i, method: :delete, class: 'button alert right' %>
                </div>
              </div>
              <div class="row">
                <% i.trip_plans.each do |t| %>
                  <%= link_to t do %>
                    <div class="col-xs-3">
                      <p class="text-center"><%= t.title %></p>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          <div class="day">
            <div class="row">
              <div class="col-xs-12">
                <%
                n = @days.max.day.to_i + 1 unless @days.empty?
                n = '1' if @days.empty?
                %>
                <%= link_to n, '#', class: 'button round secondary disabled' %>
              </div>
            <div class="row">
              <div class="col-xs-12">
                <div class="text-center">
                  <p>You don't have any plans for day #{n} yet.</p>
                  <%= link_to new_trip_plan_path, class: 'button' do %>
                    <i class="fa fa-plus"></i>&nbsp;Add Something to Day #{n}
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="panel navbar-panel">
        <h3>Pin Notes</p>
        <%= link_to new_pin_note_path, class: 'button secondary' do %>
          <i class="fa fa-plus-circle"></i>
          New
        <% end %>
      </div>
      <% @pin_notes.each do |i| %>
        <div class="note">
          <p><%= i.note %></p><br>
          <%= link_to 'Edit', edit_pin_note_path(i), class: 'button' %>
          <%= link_to 'Delete', i, method: :delete, class: 'button alert' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for [@trip, @event], html: {role: 'form', class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :date, class: 'form-control', placeholder: 'Date' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :time, class: 'form-control', placeholder: 'Time' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :duration, class: 'form-control', placeholder: 'Duration' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :place, class: 'form-control', placeholder: 'Place' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_area :notes, class: 'form-control', placeholder: 'Notes' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', root_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/events/_validation.html.erb
<div class="row block mid-full error">
  <div class="col-xs-12">
    <h3>
      <b>Oops! <%= pluralize(@event.errors.count, 'Error') %></b>
    </h3>
    <ul>
      <% @event.errors.full_messages.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/edit.html.erb
<% content_for :title do %>
  <title>Edit Event | Trip Planner</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <% if @event.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1>Edit Event</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<% content_for :title do %>
  <title>Add an Event | Trip Planner</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <% if @event.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1>Add a New Event</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :title do %>
  <title>Event Details | Trip Planner</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1><%= @event.title %></h1>
      <%= link_to trip_event_path(@event.trip_id, @event), method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'This will delete this item permanently.' } do %>
        <i class="fa fa-trash-o"></i>&nbsp;Delete
      <% end %>
      <%= link_to edit_trip_event_path(@event.trip_id, @event), class: 'btn btn-round btn-primary pull-right' do %>
        <i class="fa fa-pencil"></i>&nbsp;Edit
      <% end %>
      <%= link_to root_path, class: 'btn btn-round btn-default pull-right' do %>
        <i class="fa fa-arrow-left"></i>&nbsp;Back
      <% end %>
      <hr>
      <article>
        <section>
          <h5><b>Date:</b> <%= @event.date %></h5>
          <h5><b>Time:</b> <%= @event.time %></h5>
          <h5><b>Duration:</b> <%= @event.duration %></h5>
          <h5><b>Place:</b> <%= @event.place %></h5>
          <h5><b>Notes:</b> <%= @event.notes %></h5>
        </section>
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= yield :title %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if @while_layout %>
      <style>
        body {
          background: #ffffff;
        }
      </style>
    <% else %>
      <style>
        body {
          background: #337ab7;
        }
      </style>
    <% end %>
    <% if notice %>
      <div class="alert alert-success fade in alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger fade in alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <% if @while_layout %>
      <footer>
        <div class="container-fluid">
          <div class="row">
            <div class="col-xs-12 text-center">
              <br>
              <p class="text-muted">Copyright &copy; 2016 by Abraar Arique Diganto. All rights reserved.</p>
            </div>
          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note, html: {role: 'form', class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_area :note, class: 'form-control', placeholder: 'Note' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', root_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/notes/_validation.html.erb
<div class="row block mid-full error">
  <div class="col-xs-12">
    <h3><b>Oops! <%= pluralize(@note.errors.count, 'Error') %>:</b></h3>
    <ul>
      <% @note.errors.full_messages.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/notes/edit.html.erb
<% content_for :title do %>
  <title>Edit Note</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <% if @note.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1>Edit Note</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<% content_for :title do %>
  <title>Create New Note</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <% if @note.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1>Add a New Note</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pin_notes/_form.html.erb
<%= form_for @pin_note, html: {role: 'form', class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_area :note, class: 'form-control', placeholder: 'Note' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/pin_notes/edit.html.erb
<% content_for :title do %>
  <title>Edit Pin Note</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <% if @pin_note.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row mid-full">
    <div class="col-xs-12">
      <h1>Edit Note</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pin_notes/new.html.erb
<% content_for :title do %>
  <title>Create Pin Note</title>
<% end %>

<%= render 'trips/header' %>

<div class="container">
  <% if @pin_note.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row mid-full">
    <div class="col-xs-12">
      <h1>Add a New Note</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/trip_plans/_form.html.erb
<%= form_for @trip_plan do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Lunch at the Resturant' %>
  <%= f.label :time %>
  <%= f.text_field :time, placeholder: '2:30 PM' %>
  <%= f.label :date %>
  <%= f.number_field :date, min: '1', max: '365', placeholder: '1' %>
  <%= f.label :duration %>
  <%= f.text_field :duration, placeholder: '2 Hours' %>
  <%= f.label :notes %>
  <%= f.text_area :notes, placeholder: 'Meet Jason at the coffee shop.' %>
  <br>
  <%= link_to 'Back', :back, class: 'button secondary' %>
  <%= f.submit 'Save', class: 'button' %>
<% end %>

app/views/trip_plans/_validation.html.erb
<div class="row mid-full error">
  <div class="col-xs-12">
    <h3>
      <b>Oops! #{pluralize(@trip_plan.errors.count, 'Error')}</b>
    </h3>
    <ul>
      <% @trip_plan.errors.full_messages.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trip_plans/edit.html.erb
<% content_for :title do %>
  <title>Edit Plan | Trip Planner</title>
<% end %>

<% if @trip_plan.errors.any? %>
  <%= render 'validation' %>
<% end %>

<div class="container">
  <div class="row mid-full">
    <div class="col-xs-12">
      <h1>Edit Plan</h1>
      <hr>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/trip_plans/new.html.erb
<% content_for :title do %>
  <title>Add a Plan | Trip Planner</title>
<% end %>

<% if @trip_plan.errors.any? %>
  <%= render 'validation' %>
<% end %>

<div class="container">
  <div class="row mid-full">
    <div class="col-xs-12">
      <h1>Add a New Plan</h1>
      <hr>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/trips/_form.html.erb
<%= form_for @trip, html: {role: 'form', class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :start_date, class: 'form-control', placeholder: 'Start Date' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_field :end_date, class: 'form-control', placeholder: 'End Date' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', root_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/trips/_header.html.erb
<header>
  <div class="container-fluid">
    <div class="row no-gutter">
      <div class="col-xs-12">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to root_path, class: "navbar-brand" do %>
                <%= image_tag 'tp_small_inverted', alt: 'TP Logo', class: 'img-responsive' %>
                Trip Planner
              <% end %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li>
                  <p class="navbar-btn">
                    <%= link_to new_trip_path, class: 'btn btn-info' do %>
                      <i class="fa fa-plus"></i>&nbsp;New Trip
                    <% end %>
                  </p>
                </li>
                <li>
                  <p class="navbar-btn">
                    <%= link_to new_note_path, class: 'btn btn-info' do %>
                      <i class="fa fa-plus"></i>&nbsp;New Note
                    <% end %>
                  </p>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="fa fa-user"></i>&nbsp;My Account
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>&nbsp;Log out
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/trips/_validation.html.erb
<div class="row mid-full error">
  <div class="col-xs-12">
    <h3><b>Oops! <%= pluralize(@trip.errors.count, 'Error') %>:</b></h3>
    <ul>
      <% @trip.errors.full_messages.each do |i| %>
        <li><%= i %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trips/edit.html.erb
<% content_for :title do %>
  <title>Edit Trip</title>
<% end %>

<%= render 'header' %>

<% if @trip.errors.any? %>
  <%= render 'validation' %>
<% end %>

<div class="container">
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1>Edit Trip</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<% content_for :title do %>
  <title> Home | Trip Planner</title>
<% end %>

<%= render 'header' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <% if @trips.any? %>
        <% @trips.each do |trip| %>
          <div class="block">
            <div class="row">
              <div class="col-xs-6">
                <h2><%= trip.name %></h2>
              </div>
              <div class="col-xs-6">
                <%= link_to trip, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'This will delete this item permanently.' } do %>
                  <i class="fa fa-trash-o"></i>&nbsp;Delete
                <% end %>
                <%= link_to edit_trip_path(trip), class: 'btn btn-round btn-primary pull-right' do %>
                  <i class="fa fa-pencil"></i>&nbsp;Edit
                <% end %>
                <%= link_to new_trip_event_path(trip), class: 'btn btn-round btn-info pull-right' do %>
                  <i class="fa fa-plus"></i>&nbsp;New Event
                <% end %>
              </div>
              <div class="col-xs-12">
                <hr>
                <p>
                  <% if trip.start_date != nil %>
                    From <%= trip.start_date %>
                  <% end %>
                  <% if trip.end_date != nil %>
                    To <%= trip.end_date %>
                  <% end %>
                </p>
              </div>
            </div>
            <div class="row text-center">
              <% if trip.events.any? %>
                <% trip.events.each do |event| %>
                  <%= link_to trip_event_path(trip, event) do %>
                    <div class="event col-xs-3">
                      <p class="text-center"><%= event.title %></p>
                    </div>
                  <% end %>
                <% end %>
              <% else %>
                <p class="text-muted"><b>You don't have any events for this trip yet.</b></p>
                <%= link_to new_trip_event_path(trip), class: 'btn btn-primary' do %>
                  <i class="fa fa-plus"></i>&nbsp;Create a new event
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="no-block text-center">
          <p class="text-muted"><b>You don't have any trips yet.</b></p>
          <%= link_to new_trip_path, class: 'btn btn-primary' do %>
            <i class="fa fa-plus"></i>&nbsp;Create a new trip
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-4">
      <% if @notes.any? %>
        <% @notes.each do |note| %>
          <div class="block block-note">
            <div class="row">
              <div class="col-xs-5">
                <h4><%= note.note %></h4>
              </div>
              <div class="col-xs-7">
                <%= link_to note, method: :delete, class: 'btn btn-danger pull-right', data: { confirm: 'This will delete this item permanently.'} do %>
                  <i class="fa fa-trash-o"></i>&nbsp;Delete
                <% end %>
                <%= link_to edit_note_path(note), class: 'btn btn-primary pull-right' do %>
                  <i class="fa fa-pencil"></i>&nbsp;Edit
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="no-block text-center">
          <p class="text-muted"><b>You don't have any notes yet.</b></p>
          <%= link_to new_note_path, class: 'btn btn-primary' do %>
            <i class="fa fa-plus"></i>&nbsp;Create a new note
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<% content_for :title do %>
  <title>Create Trip</title>
<% end %>

<%= render 'header' %>

<div class="container">
  <% if @trip.errors.any? %>
    <%= render 'validation' %>
  <% end %>
  <div class="row block mid-full">
    <div class="col-xs-12">
      <h1>Add a New Trip</h1>
      <hr><br>
      <%= render 'form' %>
    </div>
  </div>
</div>